
channels:
  - defaults
dependencies:
  - python=3.9
  - r-base=4.1.2
  - r-essentials
  - r-desctools
  - r-ggpubr
  - r-ggiraph
  - r-devtools
  - r-emmeans
  - jupyterlab
  - jupyterlab_launcher
  - biopython
